annotations_csv: "./data/annotations.csv"
annotations_coco_csv: "./data/annotations_coco.csv"
training_images_path: "./data/training_nodules"
model_file: "./models/trained_model"
plots_dir: "./plots/"
predictions_dir: "./data/predictions"

seed: 42
dimension: 256
batch_size: 1
num_workers: 4
train_split: 0.8
num_epochs: 10
num_classes: 2
