raw_path: "../data/raw"
processed_path: "../data/processed"
annotations_csv: "../data/annotations.csv"
annotations_coco_csv: "../data/annotations_coco.csv"
training_images_path: "../data/training_nodules"

dimension: 256
batch_size: 4
num_workers: 4
train_split: 0.8
num_epochs: 2
num_classes: 2
